name: Add Comment on PR
description: Add a comment on the current PR
inputs:
    message:
        description: The message to post on the PR
        required: true
    avoidRepostsWith:
        description: Use this to avoid reposting the message if it is already on the PR
        required: false
runs:
    using: composite
    steps:
        - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
          env:
              COMMENT_MESSAGE: ${{ inputs.message }}
              AVOID_REPOSTS_WITH: ${{ inputs.avoidRepostsWith }}
          with:
              script: |
                  const addComment = require('./.github/actions/comment-on-pr/index.js');
                  await addComment({
                      github,
                      context,
                      message: process.env.COMMENT_MESSAGE,
                      avoidRepostsWith: process.env.AVOID_REPOSTS_WITH,
                  });
